# Generated by Django 3.2.8 on 2021-10-10 15:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoriesproduct',
            name='size',
        ),
        migrations.RemoveField(
            model_name='bagproduct',
            name='size',
        ),
        migrations.AddField(
            model_name='accessoriesproduct',
            name='available_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('One size', 'one size')], default='one', max_length=12, verbose_name='Розміра в наявності'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bagproduct',
            name='available_size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('One size', 'one size')], default='one', max_length=12, verbose_name='Розміра в наявності'),
            preserve_default=False,
        ),
    ]
