# Generated by Django 3.2.8 on 2021-10-16 08:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cities_light', '0011_auto_20211011_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамілія')),
                ('phone', models.CharField(max_length=255, verbose_name='Номер телефону')),
                ('post_office', models.CharField(max_length=255, verbose_name='Вдділення пошти')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментар до замовлення')),
                ('status', models.CharField(choices=[('STATUS_NEW', 'Нове замовлення'), ('STATUS_IN_PROCESS', 'Замовлення в процесі обробки'), ('STATUS_READY', 'Замовлення готове'), ('STATUS_COMPLETED', 'Замовлення виконане')], default='Нове замовлення', max_length=255, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення замовлення')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата доставки товару покупцю')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Корзина')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='Місто')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to=settings.AUTH_USER_MODEL, verbose_name='Покупець')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Ціна')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Замовлення')),
            ],
        ),
    ]
